import type { Metadata } from "next";
import "./globals.css";
import ThemeClientProvider from "@/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = "/fonts/Ubuntu.woff";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link key={font} rel="preload" href={font} as="font" crossOrigin="" />
        <meta httpEquiv="Content-Type" content="text/html" charSet="utf-8" />
      </head>
      <ThemeClientProvider>
        <body>{children}</body>
      </ThemeClientProvider>
    </html>
  );
}
